Fix for Invalid Token Stream error for simple queries in go driver (#4718) (#4754)
Simple queries like SELECT 1 AS test were failing on go-sqlcmd v1.9.0 with error: Invalid TDS stream: unknown token type returned: token(165) causing the session to hang. This was because TdsSendRowDescription()was sending colinfo token for regular queries. The go-mssqldb driver does not implement a parser for colinfo token, so it reports the token as unknown and the TDS stream becomes desynchronized, causing the session to hang.

Fix: Guarded SendColInfoToken() with if (relMetaDataInfoList != NIL) so it is only sent when table metadata exists. Also, added a no_browsetable check, when NO_BROWSETABLE is ON, the COLINFO token is sent, otherwise it is not sent.

Task: BABEL-6423

Authored by: Vineetha125 bvineets@amazon.com