Replace varcharTypeName->typeOid with baseTypeId in tsql_coerce_string_literal_hook() to get the correct typeId (#2235)
Currently, in tsql_coerce_string_literal_hook(), we are using varcharTypeName->typeOid without actually being set.
This leads to error while dumping objects containing cast from string literal to binary type during MVU.

For example:

-- T-SQL endpoint
1> create view babel_4475_v1 as select cast(cast('a' as binary(2)) as varchar(2))
2> go

-- PSQL endpoint
jdbc_testdb=# select pg_catalog.pg_get_viewdef(oid, true) from pg_class where relname = 'babel_4475_v1';
ERROR:  cache lookup failed for type 0


This same also being done during dump & restore. This commit aims to fix this issue by appropriately setting base type id in tsql_coerce_string_literal_hook. 

Task: BABEL-4688
Signed-off-by: Sai Rohan Basa <bsrohan@amazon.com>