pg_upgrade fails with an error "ERROR: cannot change data type of view column "definition" from nvarchar to nvarchar(4000)" (#2616)
pg_upgrade fails with an error "ERROR: cannot change data type of view column "definition" from nvarchar to nvarchar(4000)"

```
ALTER EXTENSION
ERROR:  cannot change data type of view column "definition" from nvarchar to nvarchar(4000)
```
We have changed the datatype of definition column of all_sql_modules_internal from nvarchar(4000) to nvarchar in version 2.9. In upgrade script 3.0 to 3.1, we have again defined the view  all_sql_modules_internal where definition column is of nvarchar(4000) datatype which is incorrect and causing the upgrade failure. Reference commit: https://github.com/babelfish-for-postgresql/babelfish_extensions/commit/508180ff77ad5820342aa14b834aaf013a9991ed 


Signed-off-by: Shalini Lohia <lshalini@amazon.com>