Fix valgrind warnings related to varcharvarbinary function (#2231)
Currently, we have defined the following cast functions which call varcharvarbinary C function with only 1 argument. But, in varcharvarbinary function, we are reading two arguments which might lead to memory related issues.

sys.binarysysvarchar
sys.binaryvarchar
sys.rowversionsysvarchar
sys.rowversionvarchar

This change modifies the above casts to have 3 arguments, one for input, one for typmod (integer) and the other for specifying isExplicit (boolean)

This change also replaces varcharTypeName->typeOid with baseTypeId in tsql_coerce_string_literal_hook() function as we are not setting varcharTypeName->typeOid at all which causes failure while trying to fetch the PG view definition as shown below.

Ex :
-- T-SQL endpoint
1> create view babel_4475_v1 as select cast(cast('a' as binary(2)) as varchar(2))
2> go

-- PSQL endpoint
jdbc_testdb=# select pg_catalog.pg_get_viewdef(oid, true) from pg_class where relname = 'babel_4475_v1';
ERROR:  cache lookup failed for type 0
jdbc_testdb=#

Issues Resolved: BABEL-4475
Signed-off-by: Sai Rohan Basa <bsrohan@amazon.com>